=== hadiwidjana/appium-selenium-restassured-framework/src/test/resources/RestTestData/Integration/bifrost/Department/DepartmentListSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "status": {
      "type": "integer"
    },
    "message": {
      "type": "string"
    },
    "pagination": {
      "type": "object",
      "properties": {
        "pages": {
          "type": "integer"
        },
        "per_page": {
          "type": "integer"
        },
        "page_count": {
          "type": "integer"
        },
        "total_count": {
          "type": "integer"
        },
        "links": {
          "type": "object",
          "properties": {
            "first": {
              "type": "string"
            },
            "previous": {
              "type": "string"
            },
            "current": {
              "type": "string"
            },
            "next": {
              "type": "string"
            }
          },
          "required": [
            "first",
            "previous",
            "current",
            "next"
          ]
        }
      },
      "required": [
        "pages",
        "per_page",
        "page_count",
        "total_count",
        "links"
      ]
    },
    "data": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "users": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "email": {
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "last_name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "email",
                    "first_name",
                    "last_name"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "email": {
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "last_name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "email",
                    "first_name",
                    "last_name"
                  ]
                }
              ]
            }
          },
          "required": [
            "id",
            "name",
            "users"
          ]
        }
      ]
    }
  },
  "required": [
    "status",
    "message",
    "pagination",
    "data"
  ]
}

=== hadiwidjana/appium-selenium-restassured-framework/src/test/resources/RestTestData/Integration/bifrost/PT/PTListResponse.json
{
    "status": 200,
    "message": "",
    "pagination": {
        "pages": 1,
        "per_page": 25,
        "page_count": 1,
        "total_count": 15,
        "links": {
            "first": "http://api-dev-integration.gokomodo.co/v1/api/master/payment-terms?page=1",
            "previous": "",
            "current": "http://api-dev-integration.gokomodo.co/v1/api/master/payment-terms?page=1",
            "next": ""
        }
    },
    "data": [
        {
            "id": 130,
            "erp_id": "",
            "terms": "30 Hari setelah Invoice diterima, dilengkapi dengan Berita Acara Serah Terima Barang"
        },
        {
            "id": 129,
            "erp_id": "",
            "terms": "14 Hari Kerja Setelah Pekerjaan"
        },
        {
            "id": 128,
            "erp_id": "",
            "terms": "100% Setelah Pekerjaan"
        },
        {
            "id": 127,
            "erp_id": "",
            "terms": "100% Uang Dimuka"
        },
        {
            "id": 126,
            "erp_id": "",
            "terms": "50% DP & 50% Setelah Pekerjaan"
        },
        {
            "id": 125,
            "erp_id": "",
            "terms": "No DP, Pembayaran Progress, Pekerjaan 30 Hari"
        },
        {
            "id": 124,
            "erp_id": "",
            "terms": "30% DP, 70% Progress, 5% Retensi (3 Bulan"
        },
        {
            "id": 123,
            "erp_id": "",
            "terms": "20% DP, 75% Setelah Pekerjaan Selesai dan Berita Acara di TTD, 5% Retensi"
        },
        {
            "id": 122,
            "erp_id": "",
            "terms": "50% DP & 50% COD"
        },
        {
            "id": 121,
            "erp_id": "",
            "terms": "100% Cash Before Delivery"
        },
        {
            "id": 120,
            "erp_id": "",
            "terms": "90 Hari Kerja Setelah Invoice di terima"
        },
        {
            "id": 119,
            "erp_id": "",
            "terms": "60 Hari Kerja Setelah Invoice di terima"
        },
        {
            "id": 118,
            "erp_id": "",
            "terms": "21 Hari Kerja Setelah Invoice di terima"
        },
        {
            "id": 117,
            "erp_id": "",
            "terms": "14 Hari Kerja Setelah Invoice di terima"
        },
        {
            "id": 116,
            "erp_id": "",
            "terms": "7 Hari Kerja Setelah Invoice di terima"
        }
    ]
}

=== hadiwidjana/appium-selenium-restassured-framework/src/test/resources/RestTestData/Integration/digital/Department/DepartmentListResponse.json
{
    "status": 200,
    "message": "",
    "pagination": {
        "pages": 1,
        "per_page": 25,
        "page_count": 1,
        "total_count": 2,
        "links": {
            "first": "http://api-dev-eproc.gokomodo.co/v1/api/master/departments?page=1",
            "previous": "",
            "current": "http://api-dev-eproc.gokomodo.co/v1/api/master/departments?page=1",
            "next": ""
        }
    },
    "data": [
        {
            "id": 284,
            "name": "Procurement Audit",
            "users": [
                {
                    "id": 2994,
                    "email": "day6corp@day6.co",
                    "first_name": "Day",
                    "last_name": "Six"
                },
                {
                    "id": 3047,
                    "email": "day602@mail.co",
                    "first_name": "Dinda ",
                    "last_name": "Kiranaa"
                },
                {
                    "id": 3048,
                    "email": "day603@mail.co",
                    "first_name": "Denia ",
                    "last_name": "Aditamaa"
                },
                {
                    "id": 3050,
                    "email": "day605@mail.co",
                    "first_name": "Dodi ",
                    "last_name": "Budianto"
                },
                {
                    "id": 3190,
                    "email": "day6hop@mail.com",
                    "first_name": "Day6",
                    "last_name": "HOP"
                },
                {
                    "id": 3192,
                    "email": "day6staff@mail.com",
                    "first_name": "Day 6",
                    "last_name": "Staff"
                }
            ]
        },
        {
            "id": 283,
            "name": "Departemen Procurement",
            "users": [
                {
                    "id": 2994,
                    "email": "day6corp@day6.co",
                    "first_name": "Day",
                    "last_name": "Six"
                },
                {
                    "id": 3046,
                    "email": "day601@mail.co",
                    "first_name": "Dayat ",
                    "last_name": "Pilang "
                },
                {
                    "id": 3047,
                    "email": "day602@mail.co",
                    "first_name": "Dinda ",
                    "last_name": "Kiranaa"
                },
                {
                    "id": 3049,
                    "email": "day604@mail.co",
                    "first_name": "Daniel ",
                    "last_name": "Sosiawan"
                },
                {
                    "id": 3191,
                    "email": "day6manager@mail.com",
                    "first_name": "Day 6",
                    "last_name": "Manager"
                }
            ]
        }
    ]
}

=== hadiwidjana/appium-selenium-restassured-framework/src/test/resources/RestTestData/Integration/bifrost/Department/DepartmentListResponse.json
{
    "status": 200,
    "message": "",
    "pagination": {
        "pages": 1,
        "per_page": 25,
        "page_count": 1,
        "total_count": 7,
        "links": {
            "first": "http://api-dev-integration.gokomodo.co/v1/api/master/departments?page=1",
            "previous": "",
            "current": "http://api-dev-integration.gokomodo.co/v1/api/master/departments?page=1",
            "next": ""
        }
    },
    "data": [
        {
            "id": 44,
            "name": "PR team 2",
            "users": [
                {
                    "id": 2989,
                    "email": "sakauniti1@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team1"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                }
            ]
        },
        {
            "id": 43,
            "name": "Supply Chain 2",
            "users": [
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                },
                {
                    "id": 2991,
                    "email": "sakauniti3@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team3"
                }
            ]
        },
        {
            "id": 39,
            "name": "Supply Chain",
            "users": [
                {
                    "id": 2987,
                    "email": "sakaunittest@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Test"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                }
            ]
        },
        {
            "id": 38,
            "name": "Factory Technical",
            "users": [
                {
                    "id": 2987,
                    "email": "sakaunittest@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Test"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                }
            ]
        },
        {
            "id": 37,
            "name": "CAPEX, General and AgroTechnic",
            "users": [
                {
                    "id": 2987,
                    "email": "sakaunittest@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Test"
                },
                {
                    "id": 2989,
                    "email": "sakauniti1@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team1"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                },
                {
                    "id": 2991,
                    "email": "sakauniti3@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team3"
                }
            ]
        },
        {
            "id": 36,
            "name": "Agro Department",
            "users": [
                {
                    "id": 2987,
                    "email": "sakaunittest@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Test"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                }
            ]
        },
        {
            "id": 35,
            "name": "Procurement",
            "users": [
                {
                    "id": 2987,
                    "email": "sakaunittest@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Test"
                },
                {
                    "id": 2989,
                    "email": "sakauniti1@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team1"
                },
                {
                    "id": 2990,
                    "email": "sakauniti2@mail.com",
                    "first_name": "Saka Uniti",
                    "last_name": "Team2"
                }
            ]
        }
    ]
}
